language: python

jobs:
  include:
    - services: docker
      env: CIBW_BEFORE_BUILD="prepare_linux.sh"

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  - python -m cibuildwheel --output-dir wheelhouse gdal-3.0.3/swig/python
