language: python

jobs:
  include:
    - os: osx
      language: shell
      env: CIBW_BEFORE_BUILD="brew install gdal@3.0.3"
    #- services: docker
      #env: CIBW_BEFORE_BUILD="yum -y install wget zlib-devel && wget https://github.com/OSGeo/gdal/releases/download/v3.0.3/gdal-3.0.3.tar.gz && wget https://github.com/OSGeo/PROJ/releases/download/6.3.0/proj-6.3.0.tar.gz && tar -xzf gdal-3.0.3.tar.gz && tar -xzf proj-6.3.0.tar.gz && cd proj-6.3.0 && ./configure && make && make install && cd ../gdal-3.0.3 && ./configure && make && make install"

notifications:
  email: false

env:
  global:
  - CIBW_BUILD: cp3?-*
  
install:
  - python -m pip install twine cibuildwheel==1.1.0

before_script:
  - wget https://files.pythonhosted.org/packages/77/99/adf9183a8cd02a3a4b7b35d6d3c14be1fd133801d7a2f8cc6f296f7584df/GDAL-3.0.3.tar.gz
  - tar -xzf GDAL-3.0.3.tar.gz

script:
  - ls
  - echo $CIBW_BEFORE_BUILD
  - python -m cibuildwheel --output-dir wheelhouse GDAL-3.0.3
